# Path or URL to the sample sheet (CSV format, columns: sample, unit, condition, fq1, fq2, strandedness)
samples: "test-datasets/samplesheet_test.csv"

trimming:
  activate: True

ref:
  genome: "test-datasets/reference/genome.fasta"
  annotation: "test-datasets/reference/genes_with_empty_tid.gtf"
